services:
  postgres:
    ports: [] # explicitly remove port exposure

  server:
    image: nexushr-server:latest
    build: null
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
